### ISSUE TITLE
Decorating the method

### ISSUE THREAD

**Issue by RonanCamus** [CypressNorth/.NET-WebApi-HttpStringDecodeFilter#1]
Should'nt I decorate my method with **[DecodeFilter]** instead of **[HttpStringDecodeFilter]** ?
Because your class is declared like this : "public class _DecodeFilter_ : ActionFilterAttribute"

**Comment by jonnale** [comment]
Good catch. The class declaration should be HttpStringDecodeFilter. This might have been something that was refactored that I forgot to update. Thanks for pointing it out!

**Comment by jonnale** [comment]
c15b3d01b7086b43ffa5a8772330a85b4d8266dd

**Comment by RonanCamus** [comment]
You're welcome !
Thanks for your filter, it helped me a lot :)
